name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main  # Trigger on push events to the main branch
      - beta # Trigger on push events to the beta branch
  pull_request:
    branches:
      - main  # Trigger on pull request events targeting the main branch
      - beta # Trigger on pull request events targeting the beta branch
      - refactor/paralle-test-runs # TODO: delete
  merge_group:
    types: [checks_requested]

jobs:
  run-other-tests:  # Define a job named "run-tests"
    name: Run all other tests  # Human-readable name for the job
    runs-on: ubuntu-latest  # Specify the latest Ubuntu runner for the job

    steps:
      - name: Check out Git repository  # Step to check out the repository
        uses: actions/checkout@v4  # Use the checkout action version 4

      - name: Set up Node.js  # Step to set up Node.js environment
        uses: actions/setup-node@v4  # Use the setup-node action version 4
        with:
          node-version: 20  # Specify Node.js version 20

      - name: Install Node.js dependencies  # Step to install Node.js dependencies
        run: npm ci  # Use 'npm ci' to install dependencies

      - name: pre-test # pre-test to check overrides
        run: npx vitest run --project pre 
      - name: test achievments
        run: npx vitest --project achievments
      - name: test arena
        run: npx vitest --project arena
      - name: test battle
        run: npx vitest --project battle
      - name: test battlerTags
        run: npx vitest --project battlerTags
      - name: test eggs
        run: npx vitest --project eggs
      - name: test field
        run: npx vitest --project field
      - name: test inputs
        run: npx vitest --project inputs
      - name: test localization
        run: npx vitest --project localization
      - name: test phases
        run: npx vitest --project phases
      - name: test settingMenu
        run: npx vitest --project settingMenu
      - name: test sprites
        run: npx vitest --project sprites
      - name: test ui
        run: npx vitest --project ui
      - name: test root
        run: npx vitest --project root

    run-abilities-tests:
      name: Run abilities tests
      runs-on: ubuntu-latest 
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install Node.js dependencies
          run: npm ci
        - name: pre-test
          run: npx vitest run --project pre 
        - name: test abilities
          run: npx vitest --project abilities

    run-items-tests:
      name: Run items tests
      runs-on: ubuntu-latest 
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install Node.js dependencies
          run: npm ci
        - name: pre-test
          run: npx vitest run --project pre 
        - name: test items
          run: npx vitest --project items

    run-moves-tests:
      name: Run moves tests
      runs-on: ubuntu-latest 
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install Node.js dependencies
          run: npm ci
        - name: pre-test
          run: npx vitest run --project pre 
        - name: test moves
          run: npx vitest --project moves
